/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.FlowLayout;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 *
 * @author NunoM
 */
public class MenuFunc extends javax.swing.JFrame {
    
    private static final int produto = 1;
    private static final int cliente = 2;
    private static final int venda = 3;
    private static final int lote = 4;
    private static final int marcacao= 5;
    
    private JPanel currentView=null;
    private HashMap<Integer,JPanel> views;

    /**
     * Creates new form MenuFunc
     */
    public MenuFunc() {
        initComponents();
         views=new HashMap<>();
        jPanel1.setLayout(new FlowLayout());
    }
 private void closeCurrentView(){
        if (currentView != null){
            currentView.setVisible(false);
           jPanel1.remove(currentView);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        produtos = new javax.swing.JMenu();
        ListProd = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenu();
        ListCli = new javax.swing.JMenuItem();
        vendas = new javax.swing.JMenu();
        InsVendas = new javax.swing.JMenuItem();
        lotes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        marcacoes = new javax.swing.JMenu();
        ListMarc = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(841, 567));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        produtos.setText("Produtos");

        ListProd.setText("Listar");
        ListProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProdActionPerformed(evt);
            }
        });
        produtos.add(ListProd);

        jMenuBar1.add(produtos);

        clientes.setText("Clientes");

        ListCli.setText("Listar");
        ListCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListCliActionPerformed(evt);
            }
        });
        clientes.add(ListCli);

        jMenuBar1.add(clientes);

        vendas.setText("Vendas");

        InsVendas.setText("Inserir");
        InsVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsVendasActionPerformed(evt);
            }
        });
        vendas.add(InsVendas);

        jMenuBar1.add(vendas);

        lotes.setText("Lotes");

        jMenuItem1.setText("Listar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        lotes.add(jMenuItem1);

        jMenuBar1.add(lotes);

        marcacoes.setText("Marcações");

        ListMarc.setText("Listar");
        ListMarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMarcActionPerformed(evt);
            }
        });
        marcacoes.add(ListMarc);

        jMenuBar1.add(marcacoes);

        sair.setText("Sair");
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProdActionPerformed
    
        
          if (!views.containsKey(produto)){
            
            JPanel prod = new Produtos();
            views.put(produto, prod);
            
        }
        closeCurrentView();
        currentView = views.get(produto);
        views.get(produto).setVisible(true);
        jPanel1.add(views.get(produto));
        this.repaint();
    }//GEN-LAST:event_ListProdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           if (!views.containsKey(lote)){
            
            JPanel lot= new Lotes();
            views.put(lote, lot);
            
        }
        closeCurrentView();
        currentView = views.get(lote);
        views.get(lote).setVisible(true);
        jPanel1.add(views.get(lote));
        this.repaint();
                        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ListCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListCliActionPerformed
           if (!views.containsKey(cliente)){
            
            JPanel cli= new Clientes();
            views.put(cliente, cli);
            
        }
        closeCurrentView();
        currentView = views.get(cliente);
        views.get(cliente).setVisible(true);
        jPanel1.add(views.get(cliente));
        this.repaint();
    }//GEN-LAST:event_ListCliActionPerformed

    private void InsVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsVendasActionPerformed
          if (!views.containsKey(venda)){
            
            JPanel vend= new Vendas();
            views.put(venda, vend);
            
        }
        closeCurrentView();
        currentView = views.get(venda);
        views.get(venda).setVisible(true);
        jPanel1.add(views.get(venda));
        this.repaint();
    }//GEN-LAST:event_InsVendasActionPerformed

    private void ListMarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMarcActionPerformed
      if (!views.containsKey(marcacao)){
            
            JPanel marc= new Marcacoes();
            views.put(marcacao, marc);
            
        }
        closeCurrentView();
        currentView = views.get(marcacao);
        views.get(marcacao).setVisible(true);
        jPanel1.add(views.get(marcacao));
        this.repaint();
    }//GEN-LAST:event_ListMarcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InsVendas;
    private javax.swing.JMenuItem ListCli;
    private javax.swing.JMenuItem ListMarc;
    private javax.swing.JMenuItem ListProd;
    private javax.swing.JMenu clientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu lotes;
    private javax.swing.JMenu marcacoes;
    private javax.swing.JMenu produtos;
    private javax.swing.JMenu sair;
    private javax.swing.JMenu vendas;
    // End of variables declaration//GEN-END:variables
}
