/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.FlowLayout;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.JFrame;


/**
 *
 * @author NunoM
 */
public class MenuAdmin extends javax.swing.JFrame {
    private static final int utilizadorespanel = 1;
    private static final int gerarInfopanel = 2;
  
    
    private JPanel currentView=null;
    private HashMap<Integer,JPanel> views;
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        views=new HashMap<>();
        jPanel1.setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
     private void closeCurrentView(){
        if (currentView != null){
            currentView.setVisible(false);
           jPanel1.remove(currentView);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Utilizadores = new javax.swing.JMenu();
        ListUtil = new javax.swing.JMenuItem();
        GerirInform = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        Utilizadores.setText("Utilizadores");
        Utilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilizadoresActionPerformed(evt);
            }
        });

        ListUtil.setText("Listar");
        ListUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListUtilActionPerformed(evt);
            }
        });
        Utilizadores.add(ListUtil);

        jMenuBar1.add(Utilizadores);

        GerirInform.setText("Gerir Informação");
        GerirInform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerirInformMouseClicked(evt);
            }
        });
        jMenuBar1.add(GerirInform);

        sair.setText("Sair");
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UtilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilizadoresActionPerformed
      
    }//GEN-LAST:event_UtilizadoresActionPerformed

    private void ListUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListUtilActionPerformed
         if (!views.containsKey(utilizadorespanel)){
            
            JPanel utilizadores = new ListarUtilizadores();
            views.put(utilizadorespanel, utilizadores);
            
        }
        closeCurrentView();
        currentView = views.get(utilizadorespanel);
        views.get(utilizadorespanel).setVisible(true);
        jPanel1.add(views.get(utilizadorespanel));
        this.repaint();
    }//GEN-LAST:event_ListUtilActionPerformed

    private void GerirInformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerirInformMouseClicked
         if (!views.containsKey(gerarInfopanel)){
            
            JPanel info = new GerarInfo();
            views.put(gerarInfopanel, info);
            
        }
        closeCurrentView();
        currentView = views.get(gerarInfopanel);
        views.get(gerarInfopanel).setVisible(true);
        jPanel1.add(views.get(gerarInfopanel));
        this.repaint();
    }//GEN-LAST:event_GerirInformMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GerirInform;
    private javax.swing.JMenuItem ListUtil;
    private javax.swing.JMenu Utilizadores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables
}
